### ISSUE TITLE
Un-escaped apostrophe in description

### ISSUE THREAD

**Issue by placoderm** [S73ph4n/joplin_day_review#1]
Inside the plugin interface in the app, the plugin shows like this:

![image](https://user-images.githubusercontent.com/31570884/146356110-2b8cccdd-2072-4014-baa2-8d61fa1cd486.png)

The apostrophe needs to be escaped somehow, or use a typographic glyph, `’`

**Comment by S73ph4n** [comment]
Thanks, I hadn't noticed.
It's fixed in V1.0.1.
