### ISSUE TITLE
Fork and modifications

### ISSUE THREAD

**Issue by zph** [S73ph4n/joplin_day_review#3]
Hi @S73ph4n,

Are you interested in me upstreaming changes I made in a fork of your plugin?

It's here: https://github.com/zph/joplin-plugin-day-review

High level summary of changes:
- Included a patch from other fork in order to fix link creation bug #2 
- Setup helpers for prior day review, monthly, prior monthly review, yearly and prior yearly reviews
- Setup auto-generation of reviews so I don't need to remember to create them
- Github Actions for auto-building the plugin when I tag a release
- Miscellaneous helpers for making plugin development easier (earthfile & makefile)

Are those interesting to you w/ what you want the plugin to accomplish? If so, happy to contribute them back!

Cheers,

**Comment by S73ph4n** [comment]
Hey @zph, 
Yes, those are all pretty useful improvements !
Feel free to submit a PR if you want

**Comment by zph** [comment]
Ok, I'll work on preparing a PR with a little more polished version than the `just for me quality` I had :)

**Comment by konstkhal** [comment]
Hey, how things are going here?

**Comment by zph** [comment]
Closing things out, I've stopped using joplin and didn't port it back.

If they're helpful, feel free to port back any updates from my fork https://github.com/zph/joplin-plugin-day-review with attribution 👍
